# Generated by Django 6.0.3 on 2026-04-17 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'house owner'), ('coordinator', 'main coordinator'), ('tenant', 'primary tenant')], max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('sleep_schedule', models.CharField(blank=True, max_length=20)),
                ('cleanliness_preference', models.CharField(blank=True, max_length=20)),
                ('noise_tolerance', models.CharField(blank=True, max_length=20)),
                ('guest_frequency', models.CharField(blank=True, max_length=20)),
                ('smoking_preference', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(blank=True, max_length=20)),
                ('study_habits', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
