# Generated by Django 6.0.3 on 2026-04-29 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant'), ('coordinator', 'Coordinator')], max_length=20)),
                ('rental_method', models.CharField(blank=True, choices=[('direct', 'Direct Room Rental'), ('coordinator', 'Whole Unit Rental through Coordinator')], max_length=20)),
                ('tenant_type', models.CharField(blank=True, choices=[('direct', 'Direct Tenant'), ('matching', 'Matching Tenant System')], max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('sleep_schedule', models.CharField(blank=True, max_length=20)),
                ('cleanliness', models.IntegerField(default=3)),
                ('noise_tolerance', models.IntegerField(default=3)),
                ('religion', models.CharField(blank=True, max_length=30)),
                ('study_habits', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
