# Generated by Django 6.0.3 on 2026-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_rental_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='race',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
