# Generated by Django 6.0.3 on 2026-05-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_display_name_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Username',
            new_name='username',
        ),
    ]
