# Generated by Django 6.0.5 on 2026-06-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_unit_rules_unit_bathrooms_unit_bedrooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='furnished',
            new_name='cooking_allowed',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='has_internet',
            new_name='covered_carpark',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='near_station',
            new_name='gym_room',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='pet_friendly',
            new_name='has_aircond',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='location',
        ),
        migrations.AddField(
            model_name='unit',
            name='floor_level',
            field=models.CharField(choices=[('Ground', 'Ground'), ('1-10', 'Level 1–10'), ('11-20', 'Level 11–20'), ('21-30', 'Level 21–30'), ('31+', 'Level 31+')], default=-9, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='has_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_washing_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='location_detail',
            field=models.CharField(blank=True, help_text='City / area / address details', max_length=255),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_brt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_bus_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_convenience_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_ktm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_lrt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_mall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_mrt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_shop_lots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='pet_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='private_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='security_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='shared_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='state',
            field=models.CharField(choices=[('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Kelantan', 'Kelantan'), ('Melaka', 'Melaka'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Pahang', 'Pahang'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Pulau Pinang', 'Pulau Pinang'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Selangor', 'Selangor'), ('Terengganu', 'Terengganu'), ('WP Kuala Lumpur', 'WP Kuala Lumpur'), ('WP Labuan', 'WP Labuan'), ('WP Putrajaya', 'WP Putrajaya')], default=-9, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('Studio', 'Studio'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex'), ('Condo', 'Condo'), ('Apartment', 'Apartment'), ('Terrace', 'Terrace'), ('Semi-D', 'Semi-D'), ('Bungalow', 'Bungalow'), ('Others', 'Others')], default=-9, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3-5', '3–5'), ('5+', '5+')], max_length=4),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bedrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3-5', '3–5'), ('5+', '5+')], max_length=4),
        ),
        migrations.AlterField(
            model_name='unit',
            name='size',
            field=models.CharField(blank=True, help_text='e.g. 80 m²', max_length=50, null=True),
        ),
    ]
