# Generated by Django 6.0.5 on 2026-06-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_unitrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='has_fridge',
            new_name='co_living',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='near_brt',
            new_name='extra_parking',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='near_convenience_store',
            new_name='has_surau',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='near_mall',
            new_name='multi_purpose_hall',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='near_shop_lots',
            new_name='near_mini_market',
        ),
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='has_shower',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='near_train',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='oku_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='playground',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='prefer_move_in_immediately',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='prefer_muslim_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='prefer_pet_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='prefer_smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='prefer_zero_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='property_type',
            field=models.CharField(choices=[('condo', 'Condo'), ('apartment', 'Apartment'), ('terrace', 'Terrace'), ('semi_d', 'Semi-D'), ('bungalow', 'Bungalow'), ('others', 'Others')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('master', 'Master Room'), ('middle', 'Middle Room'), ('small', 'Small Room')], default='master', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_level',
            field=models.CharField(choices=[('Ground', 'Ground'), ('1-10', 'Level 1–10'), ('11-20', 'Level 11–20'), ('21-30', 'Level 21–30'), ('31+', 'Level 31+')], default='Ground', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='location_detail',
            field=models.CharField(blank=True, help_text='Apartment name / street / extra details', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(blank=True, help_text='e.g. 450 sqft', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='unit_type',
            field=models.CharField(choices=[('Studio', 'Studio'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex'), ('Condo', 'Condo'), ('Apartment', 'Apartment'), ('Terrace', 'Terrace'), ('Semi-D', 'Semi-D'), ('Bungalow', 'Bungalow'), ('Others', 'Others')], default='Apartment', max_length=20),
        ),
    ]
