# Generated by Django 6.0.5 on 2026-06-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_rename_has_fridge_room_co_living_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='property_type',
        ),
    ]
