# Generated by Django 6.0.5 on 2026-06-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='multi_purpose_hall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='oku_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='playground',
            field=models.BooleanField(default=False),
        ),
    ]
