# Generated by Django 6.0.5 on 2026-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_unit_multi_purpose_hall_unit_oku_friendly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_level',
            field=models.IntegerField(blank=True, help_text='Enter floor number (e.g., 0 for ground, 1-5, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor_level',
            field=models.IntegerField(blank=True, help_text='Enter floor number (e.g., 0 for ground, 1-5, etc.)', null=True),
        ),
    ]
