# Generated by Django 6.0.5 on 2026-07-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_unitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='location_detail',
            field=models.CharField(blank=True, help_text='Apartment name / street / extra details', max_length=255),
        ),
    ]
