# Generated by Django 6.0.5 on 2026-07-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_unit_city_alter_unit_location_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='bathrooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bedrooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
