# Generated by Django 6.0.5 on 2026-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_alter_unit_bathrooms_alter_unit_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='co_living',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='extra_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_shower',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_surau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_mini_market',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='near_train',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='prefer_move_in_immediately',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='prefer_muslim_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='prefer_pet_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='prefer_smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='prefer_zero_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
