# Generated by Django 6.0.5 on 2026-07-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_unit_co_living_unit_extra_parking_unit_has_shower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='near_train',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='near_train',
        ),
    ]
