# Generated by Django 6.0.5 on 2026-07-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0016_remove_room_near_train_remove_unit_near_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='near_convenience_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='near_mall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='near_shop_lots',
            field=models.BooleanField(default=False),
        ),
    ]
