# Generated by Django 6.0.5 on 2026-07-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_room_near_convenience_store_room_near_mall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='near_brt',
            field=models.BooleanField(default=False),
        ),
    ]
