# Generated by Django 6.0.4 on 2026-06-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0002_alter_roommatepost_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='cleanliness',
            field=models.CharField(choices=[('any', 'Any'), ('very_clean', 'Very Clean'), ('normal', 'Normal'), ('messy', 'Messy')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='pets',
            field=models.CharField(choices=[('any', 'Any'), ('no_pets', 'No Pets'), ('pets_ok', 'Pets OK')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='sleep_schedule',
            field=models.CharField(choices=[('any', 'Any'), ('early_sleep', 'Early Sleep'), ('late_sleep', 'Late Sleep'), ('flexible', 'Flexible')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='smoking',
            field=models.CharField(choices=[('any', 'Any'), ('no_smoking', 'No Smoking'), ('smoking_ok', 'Smoking OK')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='study_preference',
            field=models.CharField(choices=[('any', 'Any'), ('quiet', 'Quiet Environment'), ('normal', 'Normal'), ('social', 'Social Environment')], default='any', max_length=20),
        ),
    ]
