# Generated by Django 6.0.4 on 2026-06-22 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0004_roommateapplication_roommatemessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roommateapplication',
            name='unique_roommate_application',
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='needed_roommates',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='post_status',
            field=models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='total_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='total_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommatepost',
            name='unit_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='roommateapplication',
            unique_together={('roommate_post', 'applicant')},
        ),
    ]
