# Generated by Django 6.0.4 on 2026-06-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0006_roommatefavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatepost',
            name='preferred_pet',
            field=models.CharField(blank=True, help_text='Example: Cats, Small Dogs, Rabbit, Fish', max_length=150),
        ),
    ]
